syntax = "proto3";

service UiServie {
  rpc Arp(ArpRequestType) returns (ArpResponseType) {}
  rpc SendArpReq(SendArpReqRequestType) returns (SendArpReqResponseType) {}
  rpc StartArpPoison(StartArpPoisonRequestType) returns (StartArpPoisonResponseType) {}
  rpc GetInterfaces(GetInterfacesRequestType) returns (GetInterfacesResponseType) {}
  rpc StartArpPoisonDetection(StartArpPoisonDetectionRequestType) returns (StartArpPoisonDetectionResponseType) {}
  rpc StartVlanHopping(StartVlanHoppingRequestType) returns (StartVlanHoppingResponseType) {}
  rpc StartDtpNegotiation(StartDtpNegotiationRequestType) returns (StartDtpNegotiationResponseType) {}
  rpc StartDtpDomainExtraction(StartDtpDomainExtractionRequestType) returns (StartDtpDomainExtractionResponseType) {}
  rpc StartMitmForwarding(StartMitmForwardingRequestType) returns (StartMitmForwardingResponseType) {}
  rpc StartDetectingWifiAps(StartDetectingWifiApsRequestType) returns (StartDetectingWifiApsResponseType) {}
  rpc StartDetectingWifiHosts(StartDetectingWifiHostsRequestType) returns (StartDetectingWifiHostsResponseType) {}
  rpc StartSendingDeauthPackets(StartSendingDeauthPacketsRequestType) returns (StartSendingDeauthPacketsResponseType) {}
  rpc StartPasswordCracking(StartPasswordCrackingRequestType) returns (StartPasswordCrackingResponseType) {}
  rpc StartWpa2HandshakeCapturing(StartWpa2HandshakeCapturingRequestType) returns (StartWpa2HandshakeCapturingResponseType) {}
  rpc GetRunningTasks(GetRunningTasksRequestType) returns (GetRunningTasksResponseType) {}
  rpc EndTask(EndTaskRequestType) returns (EndTaskResponseType) {}


}

message ArpRequestType {
  string ip = 1;
}
message ArpResponseType {
  string ip = 1;
}

message SendArpReqRequestType {
  string iface_ip = 1;
  string ip = 2;
}
message SendArpReqResponseType {}

message StartArpPoisonRequestType {
  string iface_ip = 1;
  string vic_src_ip = 2;
  string vic_dst_ip = 3;
  string forward_to_ip = 4;
}
message StartArpPoisonResponseType {}

message GetInterfacesRequestType {}
message GetInterfacesResponseType {
  repeated string devices_names = 1;
}

message StartArpPoisonDetectionRequestType {
  string iface_ip = 1;
}
message StartArpPoisonDetectionResponseType {}

message StartVlanHoppingRequestType {
  string iface_ip = 1;
  string outer_str = 2;
  string inner_str = 3;
}
message StartVlanHoppingResponseType {}

message StartDtpNegotiationRequestType {
  string iface_ip = 1;
  string domain_name = 2;
}
message StartDtpNegotiationResponseType {}

message StartDtpDomainExtractionRequestType {
  string iface_ip = 1;
}
message StartDtpDomainExtractionResponseType {
  string domain_name = 1;
}

message StartMitmForwardingRequestType {
  string iface_ip = 1;
  string victim_ip = 2;
  string gateway_ip = 3;
  string victim_mac= 4;
  string gateway_mac = 5;
}
message StartMitmForwardingResponseType {}

message StartDetectingWifiApsRequestType {
  string iface_ip = 1;
}
message StartDetectingWifiApsResponseType {
  repeated string ap_list=1;
}

message StartDetectingWifiHostsRequestType {
  string iface_ip = 1;
}
message StartDetectingWifiHostsResponseType {
  repeated string host_list=1;
}

message StartSendingDeauthPacketsRequestType {
  string iface_name = 1;
  string wifi_ap = 2;
  repeated string host_list = 3;
}
message StartSendingDeauthPacketsResponseType {}


message HandShakeDataType {

}
message StartPasswordCrackingRequestType {
  string iface_name = 1;
  HandShakeDataType handshake_data = 2;
}
message StartPasswordCrackingResponseType {}

message StartWpa2HandshakeCapturingRequestType {
  string iface_name = 1;
  HandShakeDataType handshake_data = 2;
}
message StartWpa2HandshakeCapturingResponseType {}

message GetRunningTasksRequestType {}
message GetRunningTasksResponseType {
  repeated int32 task_ids = 1;
}

message EndTaskRequestType {
  int32 id = 1;
}
message EndTaskResponseType {}

