
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/media/dev/H/clion-2024.3/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.1.0-31-amd64 - x86_64
...
